#priority 15

import crafttweaker.item.IItemStack;
import loottweaker.LootTweaker;
import loottweaker.vanilla.loot.LootTable;
import loottweaker.vanilla.loot.LootPool;

function add_ammo_and_weapon (loot_table as string, min_value as int, max_value as int) {
	val table_as_table = LootTweaker.getTable(loot_table);
	val pool = table_as_table.addPool("custom_guns", min_value, max_value, 0, 0);
	pool.addItemEntry(<flansmod:dwambirconsteamrifleammo>, 50);
	pool.addItemEntry(<flansmod:dwsf94auammo>, 50);
	pool.addItemEntry(<flansmod:rusty_queen_ammo_clip>, 50);
	pool.addItemEntry(<flansmod:dwpwrammo>, 50);
	pool.addItemEntry(<flansmod:dwskylighteraecammo>, 50);
	pool.addItemEntry(<flansmod:dwcinderfireammo>, 50);
	pool.addItemEntry(<flansmod:dwmbtcrossbowammo>, 50);
	pool.addItemEntry(<flansmod:dwpepperboxammo>, 50);
	pool.addItemEntry(<flansmod:dwbreacher870ammo>, 50);
	pool.addItemEntry(<flansmod:dwwinnowammo>, 50);
	pool.addItemEntry(<flansmod:dwmfp15ammo>, 50);
	pool.addItemEntry(<flansmod:dwgs5ammo>, 50);
	pool.addItemEntry(<flansmod:dwwolfstedtammo>, 50);
	pool.addItemEntry(<flansmod:dwpup227ammo>, 50);
	pool.addItemEntry(<flansmod:dw40mmfrag>, 50);
	pool.addItemEntry(<flansmod:dw40mmsmoke>, 50);
	pool.addItemEntry(<flansmod:dw40mmgas>, 50);
	pool.addItemEntry(<flansmod:dwstumbreonsvammo>, 25);
	pool.addItemEntry(<flansmod:dwsf94ammo>, 25);
	pool.addItemEntry(<flansmod:atol_ammo_clip>, 25);
	pool.addItemEntry(<flansmod:supressor_ammo_clip>, 25);
	pool.addItemEntry(<flansmod:dwdusterwingammo>, 25);
	pool.addItemEntry(<flansmod:dwsc7stndammo>, 25);
	pool.addItemEntry(<flansmod:dwhvfpeforatorammo>, 25);
	pool.addItemEntry(<flansmod:dwsforelammo>, 25);
	pool.addItemEntry(<flansmod:shooter_ammo_clip>, 25);
	pool.addItemEntry(<flansmod:dwfeathershockammo>, 25);
	pool.addItemEntry(<flansmod:dwsteelblussammo>, 25);
	pool.addItemEntry(<flansmod:dwshotgunpelletammo>, 25);
	pool.addItemEntry(<flansmod:dwsc7ammo>, 25);
	pool.addItemEntry(<flansmod:dwmfp33ammo>, 25);
	pool.addItemEntry(<flansmod:handgun_ammo_clip>, 25);
	pool.addItemEntry(<flansmod:dwsilversecammo>, 25);
	pool.addItemEntry(<flansmod:dwat51spammo>, 25);
	pool.addItemEntry(<flansmod:dwmapmpammo>, 25);
	pool.addItemEntry(<flansmod:dwmfp5compactammo>, 25);
	pool.addItemEntry(<flansmod:goplon_repeater_clip>, 25);
	pool.addItemEntry(<flansmod:dw40mmfrag>, 25);
	pool.addItemEntry(<flansmod:dw40mmsmoke>, 25);
	pool.addItemEntry(<flansmod:dw40mmgas>, 25);
	pool.addItemEntry(<flansmod:dwmatriarchscatterammo>, 25);
	pool.addItemEntry(<flansmod:dwmatriarchsnubshortammo>, 25);
	pool.addItemEntry(<flansmod:dwambirconsteamrifle>, 25);
	pool.addItemEntry(<flansmod:dwsf94au>, 5);
	pool.addItemEntry(<flansmod:rusty_queen>, 5);
	pool.addItemEntry(<flansmod:dwpwr57>, 5);
	pool.addItemEntry(<flansmod:dwskylighteraec>, 5);
	pool.addItemEntry(<flansmod:dwcinderfire>, 5);
	pool.addItemEntry(<flansmod:dwmbtcrossbow>, 5);
	pool.addItemEntry(<flansmod:dwpepperbox>, 5);
	pool.addItemEntry(<flansmod:dwbreacher870>, 5);
	pool.addItemEntry(<flansmod:dwwinnow>, 5);
	pool.addItemEntry(<flansmod:dwmfp15>, 5);
	pool.addItemEntry(<flansmod:dwgs5>, 5);
	pool.addItemEntry(<flansmod:dwwolfstedt>, 5);
	pool.addItemEntry(<flansmod:dwpup227>, 5);
	pool.addItemEntry(<flansmod:dwmodcannonlauncher>, 5);
	pool.addItemEntry(<flansmod:dwkgl40>, 5);
	pool.addItemEntry(<techguns:thompson>, 10);
	pool.addItemEntry(<techguns:revolver>, 10);
	pool.addItemEntry(<techguns:sawedoff>, 10);
	pool.addItemEntry(<techguns:handcannon>, 10);
	pool.addItemEntry(<flansmod:dwstumbreonsv>, 1);
	pool.addItemEntry(<flansmod:dwsf94>, 1);
	pool.addItemEntry(<flansmod:atol_rifle>, 1);
	pool.addItemEntry(<flansmod:supressor>, 1);
	pool.addItemEntry(<flansmod:dwdusterwing>, 1);
	pool.addItemEntry(<flansmod:dwsc7stnd>, 1);
	pool.addItemEntry(<flansmod:dwhvfpeforator>, 1);
	pool.addItemEntry(<flansmod:dwsforel>, 1);
	pool.addItemEntry(<flansmod:shooter>, 1);
	pool.addItemEntry(<flansmod:dwfeathershock>, 1);
	pool.addItemEntry(<flansmod:dwsteelbluss>, 1);
	pool.addItemEntry(<flansmod:dwkp12>, 1);
	pool.addItemEntry(<flansmod:dwflakwater>, 1);
	pool.addItemEntry(<flansmod:dwsc7>, 1);
	pool.addItemEntry(<flansmod:dwmfp33>, 1);
	pool.addItemEntry(<flansmod:handgun>, 1);
	pool.addItemEntry(<flansmod:dwsilversec>, 1);
	pool.addItemEntry(<flansmod:dwat51sp>, 1);
	pool.addItemEntry(<flansmod:dwmapmp>, 1);
	pool.addItemEntry(<flansmod:dwmfp5compact>, 1);
	pool.addItemEntry(<flansmod:goplon_repeater>, 1);
	pool.addItemEntry(<flansmod:dwkgl3>, 1);
	pool.addItemEntry(<flansmod:dwpagl>, 1);
	pool.addItemEntry(<flansmod:dwmatriarchscatter>, 1);
	pool.addItemEntry(<flansmod:dwmatriarchsnubshort>, 1);
	pool.addItemEntry(<techguns:ak47>, 1);
	pool.addItemEntry(<techguns:goldenrevolver>, 1);
	pool.addItemEntry(<techguns:m4>, 1);
	pool.addItemEntry(<techguns:mac10>, 1);
	pool.addItemEntry(<techguns:combatshotgun>, 1);
	pool.addItemEntry(<techguns:pistol>, 1);
	pool.addItemEntry(<techguns:m4_infiltrator>, 1);
	pool.addItemEntry(<techguns:boltaction>, 1);
}

function ammo_only (loot_table as string, min_value as int, max_value as int) {
	val table_as_table = LootTweaker.getTable(loot_table);
	val pool = table_as_table.addPool("custom_ammo", min_value, max_value, 0, 0);
	pool.addItemEntry(<flansmod:dwambirconsteamrifleammo>, 50);
	pool.addItemEntry(<flansmod:dwsf94auammo>, 50);
	pool.addItemEntry(<flansmod:rusty_queen_ammo_clip>, 50);
	pool.addItemEntry(<flansmod:dwpwrammo>, 50);
	pool.addItemEntry(<flansmod:dwskylighteraecammo>, 50);
	pool.addItemEntry(<flansmod:dwcinderfireammo>, 50);
	pool.addItemEntry(<flansmod:dwmbtcrossbowammo>, 50);
	pool.addItemEntry(<flansmod:dwpepperboxammo>, 50);
	pool.addItemEntry(<flansmod:dwbreacher870ammo>, 50);
	pool.addItemEntry(<flansmod:dwwinnowammo>, 50);
	pool.addItemEntry(<flansmod:dwmfp15ammo>, 50);
	pool.addItemEntry(<flansmod:dwgs5ammo>, 50);
	pool.addItemEntry(<flansmod:dwwolfstedtammo>, 50);
	pool.addItemEntry(<flansmod:dwpup227ammo>, 50);
	pool.addItemEntry(<flansmod:dw40mmfrag>, 50);
	pool.addItemEntry(<flansmod:dw40mmsmoke>, 50);
	pool.addItemEntry(<flansmod:dw40mmgas>, 50);
	pool.addItemEntry(<flansmod:dwstumbreonsvammo>, 25);
	pool.addItemEntry(<flansmod:dwsf94ammo>, 25);
	pool.addItemEntry(<flansmod:atol_ammo_clip>, 25);
	pool.addItemEntry(<flansmod:supressor_ammo_clip>, 25);
	pool.addItemEntry(<flansmod:dwdusterwingammo>, 25);
	pool.addItemEntry(<flansmod:dwsc7stndammo>, 25);
	pool.addItemEntry(<flansmod:dwhvfpeforatorammo>, 25);
	pool.addItemEntry(<flansmod:dwsforelammo>, 25);
	pool.addItemEntry(<flansmod:shooter_ammo_clip>, 25);
	pool.addItemEntry(<flansmod:dwfeathershockammo>, 25);
	pool.addItemEntry(<flansmod:dwsteelblussammo>, 25);
	pool.addItemEntry(<flansmod:dwshotgunpelletammo>, 25);
	pool.addItemEntry(<flansmod:dwsc7ammo>, 25);
	pool.addItemEntry(<flansmod:dwmfp33ammo>, 25);
	pool.addItemEntry(<flansmod:handgun_ammo_clip>, 25);
	pool.addItemEntry(<flansmod:dwsilversecammo>, 25);
	pool.addItemEntry(<flansmod:dwat51spammo>, 25);
	pool.addItemEntry(<flansmod:dwmapmpammo>, 25);
	pool.addItemEntry(<flansmod:dwmfp5compactammo>, 25);
	pool.addItemEntry(<flansmod:goplon_repeater_clip>, 25);
	pool.addItemEntry(<flansmod:dwmatriarchscatterammo>, 25);
	pool.addItemEntry(<flansmod:dwmatriarchsnubshortammo>, 25);
	pool.addItemEntry(<flansmod:dwambirconsteamrifle>, 25);
}

function explosives_only (loot_table as string, min_value as int, max_value as int) {
	val table_as_table = LootTweaker.getTable(loot_table);
	val pool = table_as_table.addPool("custom_explosives", min_value, max_value, 0, 0);
	pool.addItemEntry(<flansmod:dwshockskymare>, 15);
	pool.addItemEntry(<flansmod:dwfraglupine>, 15);
	pool.addItemEntry(<flansmod:dwfragambircon>, 15);
	pool.addItemEntry(<flansmod:dwskyswattertrackammo>, 15);
	pool.addItemEntry(<flansmod:dwfragskymare>, 15);
	pool.addItemEntry(<flansmod:dwsmokeambircon>, 15);
	pool.addItemEntry(<flansmod:dwflashambircon>, 15);
	pool.addItemEntry(<flansmod:dwlupinec4>, 15);
	pool.addItemEntry(<flansmod:dwrocketlupine>, 15);
	pool.addItemEntry(<flansmod:dwflamelupine>, 15);
	pool.addItemEntry(<flansmod:dwflamelupine>, 15);
}

add_ammo_and_weapon("minecraft:chests/abandoned_mineshaft", 1, 2);
add_ammo_and_weapon("minecraft:chests/desert_pyramid", 1, 2);
add_ammo_and_weapon("minecraft:chests/jungle_temple", 1, 2);
add_ammo_and_weapon("minecraft:chests/simple_dungeon", 1, 2);
add_ammo_and_weapon("minecraft:chests/stronghold_corridor", 1, 2);
add_ammo_and_weapon("minecraft:chests/stronghold_crossing", 1, 2);
add_ammo_and_weapon("techguns:blocks/military_crate_gun", 3, 6);
add_ammo_and_weapon("techguns:blocks/military_crate_generic", 1, 2);
add_ammo_and_weapon("techguns:chests/survivor_hideout", 1, 2);

ammo_only("techguns:blocks/military_crate_ammo", 6, 5);
explosives_only("techguns:blocks/military_crate_explosives", 3, 6);